# Generated by Django 2.2.7 on 2019-12-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=140, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('img', models.ImageField(blank=True, max_length=255, null=True, upload_to='avatar_image', verbose_name='avatar')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('s_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Surname')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
